id: P46468394
initial_creation_type: input
source_metadata:
  title: Dilgo Khyentse Rinpoche Series
  language: it
  description: 'Texts by and about Kyabje Dilgo Khyentse Rinpoche, Tashi Paljor (dil
    mgo mkhyen brtse bkra shis dpal ''byor, 1910-1991):'
  volume:
    eb3e5daeff294bbbbf8f292cebc3611b:
      title: Advice to Three-Year Retreatants
      parent: Advice
    a41e750f68c64dcb865ad9d7ea5346eb:
      title: Heart Advice in Four Lines
      parent: Advice
    043ac9cf91664967b413b5b95efa9744:
      title: Letter of Advice to Jamyang Gyaltsen
      parent: Advice
    aecfb3f762e04cbd9fb229065514b7db:
      title: A Prayer for the Spread of Kyabje Dilgo Khyentse Rinpoche’s Termas
      parent: Aspiration Prayers
    22cc07a783784e26b9d338f0377dbd5e:
      title: 'The Blissful Path to the Ocean of Bodhichitta: A Brief Prayer of Aspiration
        for Mind Training'
      parent: Aspiration Prayers
    2c9225a811844c329b0e67bb8d5feeed:
      title: 'The Vidyādharas'' Words of Truth: An Aspiration Connected with the Stages
        of the Path of the Three Roots, from the Heart Essence of the Vast Expanse'
      parent: Aspiration Prayers
    969dfbc42dbe4abd8f57e605c919d32b:
      title: 'Wisdom''s Melody: An Aspiration to Realize Madhyamaka, Mahāmudrā, and
        Mahā Ati'
      parent: Aspiration Prayers
    03a28c6881ab4d5ab22cad40143c6584:
      title: 'Wondrous Light of Lunar Nectar: The Biography of Chatral Kunga Palden,
        a Yogin of the Supreme Vehicle'
      parent: Biographies
    91e55e6525e84998976d59bc8fd9b2b3:
      title: Calling the Guru From Afar
      parent: Calling the Guru from Afar
    2fea61f987c54cf7b60286c98d2f8b7a:
      title: Calling the Guru from Afar
      parent: Calling the Guru from Afar
    00290fd9bd89431ca644c607603e09e5:
      title: 'Nectar Shower of Blessings: A Song of Yearning Devotion Recalling the
        Everpresent Gurus'
      parent: Calling the Guru from Afar
    ad811e60bf10492eb42fc2b942f32339:
      title: 'Repository of Every Form of Dharma That Might Be Wished For: A Catalogue
        to the Published Miscellaneous Writings of the Venerable Guru Jamyang Chökyi
        Lodrö'
      parent: Catalogues
    120732e8aa5a4057a993c8a16bada5a0:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chöd
    b0869183e7414db9b05806864cf4e7ce:
      title: 'The Sage who Dispels Mind’s Anguish: Advice from the Guru, the Gentle
        Protector Mañjuśrī on the Means of Accomplishing the Yogas of Śamatha and
        Vipaśyanā'
      parent: Commentaries
    ec87d0da438642c2ae274ee96959f1f6:
      title: 'Shower of Indestructible Splendour: A Self-Initiation for the Guru Practice
        of the Vidyādhara Assembly, from the Heart-Essence of the Vast Expanse'
      parent: Empowerment Rites
    55d0a818295a40ac95558130cd606894:
      title: 'A Garland of Vajra Words: A Prayer to the Guru'
      parent: Guru Rinpoche Prayers
    64b799006a7847f187cbca0c7b752065:
      title: 'All Wishes Swiftly Fulfilled: A Prayer to the Mahāguru of Uḍḍiyāna in
        Eight Chapters'
      parent: Guru Rinpoche Prayers
    cbf0147d4e1542e4b101cd984e2099a3:
      title: Guru Yoga – A Rang Rig Ma Chö
      parent: Guru Yoga
    d3809d7b510b480a945c8b4880a2a966:
      title: 'Guru Yoga: The Complete Path of Sūtra And Tantra'
      parent: Guru Yoga
    f314b2d9e76a49a988885ebb0fd6feed:
      title: 'The Quintessence of the Profound Path: A Concise Guide to the Stages
        of Visualization for the Guru Yoga of the Seven-Line Supplication, A Shower
        of Blessings'
      parent: Guru Yoga
    c8341b77d15f4d00a4dd17ab0fee00c7:
      title: 'The Sun of Ambrosial Wisdom: A Guru Yoga of Dharmarāja Sakya Paṇḍita'
      parent: Guru Yoga
    92d84e4005014c2898c6df74e860bc41:
      title: A History of Dzongsar Monastery
      parent: History
    bf697c1abea345d9b5c55b70ecc14ecc:
      title: 'Beautiful Clouds of Blessings: A Prayer to the Lineage Masters of the
        Heart Essence of the Vast Expanse from the Great Perfection'
      parent: Lineage Prayers
    bb51a2d2ce544928a85b2de17e653db8:
      title: Prayer to Longchenpa (Adapted from the Words of Mipham Rinpoche)
      parent: Lineage Prayers
    eab3f148631143738761acb1a8f542f3:
      title: Supplication to the Lineage of the Heart Essence of the Vast Expanse
      parent: Lineage Prayers
    bb4b862d686e4a208e0726ba1d23c875:
      title: 'Vajrakīla Prayer: A Rain of Accomplishments'
      parent: Lineage Prayers
    1360d167cb8348139fe44ea48597504e:
      title: Ambrosia for the Mind
      parent: Lojong
    cfef4eff3f3e4d6cb6db1b7f674cb442:
      title: Prayer for the Long Life of Dzongsar Jamyang Khyentse Rinpoche
      parent: Long Life Prayers
    f8ad21091729471da421da2a89fbe024:
      title: Prayer for the Long Life of Shechen Rabjam Rinpoche
      parent: Long Life Prayers
    cea252706b3c4fd48d739eaefc58b13d:
      title: 'The Vajra Sitar of Immortality: A Prayer for the Long Life of the Fourth
        Incarnation of Terchen Chokgyur Lingpa'
      parent: Long Life Prayers
    f1af7dc72552465aae887fe0426f7afe:
      title: 'True Words to Accomplish Immortality: A Longevity Prayer to the Tulku
        of Jamyang Khyentse, Thupten Chökyi Gyatso'
      parent: Long Life Prayers
    cc802a682d4943ef97c559563722c292:
      title: A Prayer to Dilgo Khyentse Rinpoche
      parent: Prayers
    e184e82b6b5e4978913c5ec91afecc0c:
      title: A Prayer to Kyabje Dilgo Khyentse Rinpoche
      parent: Prayers
    34f5b99aa59a4d9f9348d1b676935220:
      title: Invocation of the Vidyādhara Gurus
      parent: Prayers
    1c6913e618aa4ece9250350a8d1cf257:
      title: 'Light of Compassion: A Prayer to the Wisdom Ḍākinīs'
      parent: Prayers
    193ff1b1344c4a299f9bb7e412c199fb:
      title: Prayer for the Fulfilment of Aspirations
      parent: Prayers
    9d284b8f766f42d2972b58bac0efbd56:
      title: Prayer to Khandro Tsering Chödrön
      parent: Prayers
    6057529266b9488bbc9fb3ab6d7ad3d8:
      title: 'The Lotus of Faith: A Supplication to the Successive Lives of Shechen
        Rabjam'
      parent: Prayers
    08ed8361ac1442d6b22d85dbdf45e2fa:
      title: 'The Potent Nectar of Accomplishment: A Prayer and Supplication to the
        Vidyādhara Gurus of the Three Lineages'
      parent: Prayers
    226258ce933949da86a78e946d6e86fd:
      title: The Prayer to Swiftly Fulfil All Wishes
      parent: Prayers
    4ac66c7585cc415eae275ed6b005559e:
      title: 'The Precious Jewel Essence: A Prayer of the Four Dharmas'
      parent: Prayers
    c6e1f383cb1c41dfa57dec54c2866b57:
      title: 'The Quintessence of Marvellous Nectar: A Prayer Based on the Liberational
        Life of the Gentle Protector Guru'
      parent: Prayers
    1e25425071df4eaebd0c124ffd2f3e5d:
      title: 'The Swift Bestowal of Blessings: A Prayer to the Glorious Protector
        Guru'
      parent: Prayers
    7217869257b049e3b003ad338fb3f4e6:
      title: A Sādhana of Golden Mañjughoṣa
      parent: Sādhanas
    71d600f3632e43f1b8813e0a84d8af50:
      title: A Sādhana of Tārā Sarasvatī
      parent: Sādhanas
    dcfb295e552149548438dc172eb7279b:
      title: Concise Daily Practice of Vajrasattva
      parent: Sādhanas
    8e3401b032ac489e9110d9a98e361501:
      title: Daily Practice of Guru Rinpoche, Buddha of Medicine
      parent: Sādhanas
    6ca18ef9b5374c3483e9525b56817851:
      title: 'The Refined Essence of Compassion: A Daily Sādhana for the Natural Liberation
        of Suffering, the Secret Practice of the Great Compassionate One'
      parent: Sādhanas
    a107db907dc644c3bc9156272341d179:
      title: Lamenting Prayer to Jamyang Chökyi Lodrö
      parent: Swift Rebirth Prayers
    85651ea674d0447da551669803006605:
      title: 'Bestowing the Glory of Wisdom: A Gaṇacakra Feast for Nyingtik Saldrön'
      parent: Tsok Offering
created_at: '2022-02-28T22:53:20.379754'
last_modified_at: '2022-02-28T22:53:20.379756'
